language: node_js

node_js:
  - 10

services:
  - docker

addons:
  sonarcloud:
    organization: ase2019-blue

script:
  - npm test -- --coverage
  - sonar-scanner
  - npm run lint

before_deploy:
  - docker build --no-cache -t christianfries/thingy-api-blue:${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push christianfries/thingy-api-blue:${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}

deploy:
  provider: script
  script: bash .travis/deploy_develop.sh
  on:
    branch: develop

before_install:
  - openssl aes-256-cbc -K $encrypted_db5fe3a4ccc4_key -iv $encrypted_db5fe3a4ccc4_iv -in .travis/id_rsa.enc -out .travis/id_rsa -d
  - ls
  - ls .travis
